{{ include "common.storage.hostPathValidate" .Values }}
apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    app: {{ template "common.names.name" . }}
    chart: {{ template "common.names.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  replicas: {{ (default 1 .Values.replicas) }}
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: {{ template "common.names.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "common.names.fullname" . }}
      labels:
        app: {{ template "common.names.name" . }}
        release: {{ .Release.Name }}
        {{- include "common.labels.selectorLabels" . | nindent 8 }}
      annotations: {{ include "common.annotations" . | nindent 8 }}
    spec:
      hostNetwork: false
      containers:
        - name: {{ .Chart.Name }}
          {{ include "common.resources.limitation" . | nindent 10 }}
          {{ include "common.containers.imageConfig" .Values.image | nindent 10 }}
          volumeMounts: {{ include "common.storage.configureAppVolumeMountsInContainer" .Values | nindent 12 }}
          {{ range $index, $hostPathConfiguration := .Values.extraAppVolumeMounts }}
            - name: extrappvolume-{{ $index }}
              mountPath: {{ $hostPathConfiguration.mountPath }}
          {{ end }}
{{ if .Values.vpn_enabled }}
          securityContext:
            privileged: true
{{ end}}
          ports:
            - name: web
              containerPort: {{ .Values.web_port }}
            - name: tcp
              containerPort: {{ .Values.tcp_port }}
              protocol: TCP
            - name: udp
              containerPort: {{ .Values.udp_port }}
              protocol: UDP
            - name: privoxy
              containerPort: {{ .Values.privoxy_port }}
              protocol: TCP
          env:
            {{ $envList := (default list .Values.environmentVariables) }}
            {{ $envList = mustAppend $envList (dict "name" "PUID" "value" (printf "%d" (.Values.ownerUID | int))) }}
            {{ $envList = mustAppend $envList (dict "name" "PGID" "value" (printf "%d" (.Values.ownerGID | int))) }}
            {{ $envList = mustAppend $envList (dict "name" "TZ" "value" (printf "%s" .Values.timezone)) }}
            {{ $envList = mustAppend $envList (dict "name" "WEBUI_PORT" "value" (printf "%d" (.Values.web_port | int))) }}
            {{ if .Values.vpn_enabled }}
            {{ $envList = mustAppend $envList (dict "name" "VPN_ENABLED" "value" "yes" ) }}
            {{ $envList = mustAppend $envList (dict "name" "VPN_USER" "value" (printf "%s" .Values.vpn_user)) }}
            {{ $envList = mustAppend $envList (dict "name" "VPN_PASS" "value" (printf "%s" .Values.vpn_pass)) }}
            {{ $envList = mustAppend $envList (dict "name" "VPN_PROV" "value" (printf "%s" .Values.vpn_prov)) }}
            {{ $envList = mustAppend $envList (dict "name" "VPN_CLIENT" "value" (printf "%s" .Values.vpn_client)) }}
            {{ $envList = mustAppend $envList (dict "name" "STRICT_PORT_FORWARD" "value" (printf "%s" .Values.vpn_strict_port_forward)) }}
            {{ $envList = mustAppend $envList (dict "name" "VPN_INPUT_PORTS" "value" (printf "%d" .Values.vpn_input_ports | int )) }}
            {{ $envList = mustAppend $envList (dict "name" "VPN_OUTPUT_PORTS" "value" (printf "%d" .Values.vpn_output_ports |int )) }}
            {{ $envList = mustAppend $envList (dict "name" "ENABLE_PRIVOXY" "value" (printf "%s" .Values.vpn_enable_privoxy)) }}
            {{ $envList = mustAppend $envList (dict "name" "LAN_NETWORK" "value" (printf "%s" .Values.vpn_lan_network)) }}
            {{ $envList = mustAppend $envList (dict "name" "NAME_SERVERS" "value" (printf "%s" .Values.vpn_dns)) }}
            {{ $envList = mustAppend $envList (dict "name" "DEBUG" "value" (printf "%s" .Values.vpn_debug)) }}
            {{ else }}
            {{ $envList = mustAppend $envList (dict "name" "VPN_ENABLED" "value" "no" ) }}
            {{ end}}
            {{ include "common.containers.environmentVariables" (dict "environmentVariables" $envList) | nindent 12 }}
{{ include "common.networking.dnsConfiguration" .Values | nindent 6 }}
      volumes: {{ include "common.storage.configureAppVolumes" .Values | nindent 8 }}
      {{ range $index, $hostPathConfiguration := .Values.extraAppVolumeMounts }}
        - name: extrappvolume-{{ $index }}
          hostPath:
            path: {{ $hostPathConfiguration.hostPath }}
      {{ end }}
